### ISSUE TITLE
got 401 during URL processing

### ISSUE THREAD

**Issue by U81-A** [Sustech-yx/WeiBanCourseMaster#2]
PS D:\Donwload\WeiBanCourseMaster-master\WeiBanCourseMaster-master> python -m pdb main.py     
> d:\donwload\weibancoursemaster-master\weibancoursemaster-master\main.py(1)<module>()
-> import time
(Pdb) a
(Pdb) c
start the programme
step2: list category
Traceback (most recent call last):
  File "C:\Users\wh_ne\AppData\Local\Programs\Python\Python311\Lib\pdb.py", line 1775, in main
    pdb._run(target)
  File "C:\Users\wh_ne\AppData\Local\Programs\Python\Python311\Lib\pdb.py", line 1643, in _run
    self.run(target.code)
  File "C:\Users\wh_ne\AppData\Local\Programs\Python\Python311\Lib\bdb.py", line 600, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "D:\Donwload\WeiBanCourseMaster-master\WeiBanCourseMaster-master\main.py", line 185, in <module>
    main()
  File "D:\Donwload\WeiBanCourseMaster-master\WeiBanCourseMaster-master\main.py", line 114, in main
    categoryInfoRaw = process_url(url, param)
                      ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Donwload\WeiBanCourseMaster-master\WeiBanCourseMaster-master\main.py", line 43, in process_url
    temp = __process_url(URL, PARAM, METHOD)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Donwload\WeiBanCourseMaster-master\WeiBanCourseMaster-master\main.py", line 66, in __process_url
    responseStream = request.urlopen(req)
                     ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wh_ne\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wh_ne\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wh_ne\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\wh_ne\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wh_ne\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "C:\Users\wh_ne\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401:
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> c:\users\wh_ne\appdata\local\programs\python\python311\lib\urllib\request.py(643)http_error_default()
-> raise HTTPError(req.full_url, code, msg, hdrs, fp)

**Comment by Sustech-yx** [comment]
没能复现你的问题。猜测可能是X_Token没搞对。

**Comment by U81-A** [comment]
谢谢谢谢，已解决。
你猜测是对的，X token搞好了就好
